DROP TABLE IF EXISTS "access_list";

DROP TABLE IF EXISTS "constraint";

DROP TABLE IF EXISTS "object";

DROP TABLE IF EXISTS "entity";

DROP TABLE IF EXISTS "param";

DROP TABLE IF EXISTS "sketch";

DROP TABLE IF EXISTS "plane";

DROP TABLE IF EXISTS "model";

DROP TABLE IF EXISTS "user";
