DROP TABLE IF EXISTS user_ CASCADE;
DROP TABLE IF EXISTS model CASCADE;
DROP TABLE IF EXISTS access_list;
DROP TABLE IF EXISTS plane CASCADE;
DROP TABLE IF EXISTS sketch CASCADE;
DROP TABLE IF EXISTS param CASCADE;
DROP TABLE IF EXISTS entity CASCADE;
DROP TABLE IF EXISTS object_ CASCADE;
DROP TABLE IF EXISTS constraint_ CASCADE;